fix: reorder CMakeLists.txt - find_library before target_link_libraries
- find_library(log-lib log) was placed after target_link_libraries
- This caused $log-lib to be empty during linking, resulting in
  undefined reference to __android_log_print